import type { Locale } from "./types";

type Text = { title: string; short: string; blurb: string };
type Act = { title: string; blurb: string };

const UNIT: Record<Exclude<Locale, "en">, Record<string, Text>> = {
  es: {
    u1: { title: "Construir una comunidad matemática con el ciclo de datos", short: "Ciclo de datos", blurb: "Cuenta lo que ves. Junta y organiza datos. Nombra lo que falta." },
    u2: { title: "Valor posicional / suma y resta, parte 1", short: "Valor posicional", blurb: "Lee, escribe, arma, compara y ordena números hasta los miles — hasta seis dígitos." },
    u3: { title: "Multiplicación y división parte 1 — sentido con modelos", short: "Sentido con modelos", blurb: "Grupos iguales, arreglos y hechos relacionados. Primero el significado." },
    u4: { title: "Geometría", short: "Geometría", blurb: "Identifica, describe, clasifica y compara. Une y parte triángulos y cuadriláteros." },
    u5: { title: "Fracciones, parte 1", short: "Fracciones 1", blurb: "Propias, impropias y mixtas. Modelos de región y de longitud." },
    u6: { title: "Hechos fundacionales de multiplicar y dividir", short: "Hechos fáciles", blurb: "0, 1, 2, 5 y 10. Pictogramas con clave." },
    u7: { title: "Suma y resta parte 2 — analizar el mundo y resolver", short: "Resolver problemas", blurb: "Historias, gráficas y patrones. Estima y resuelve hasta 1 000." },
    u8: { title: "Medición, perímetro y área", short: "Medición", blurb: "Longitud, masa y volumen — sistema usual y métrico. Luego cubre y rodea." },
    u9: { title: "Hechos de 3, 4, 8 y 9", short: "3 4 8 9", blurb: "Tablas de 3, 4, 8 y 9 en grupos y arreglos." },
    u10: { title: "Fracciones, parte 2", short: "Fracciones 2", blurb: "Equivalentes, comparar, puntos de referencia y orden." },
    u11: { title: "Tiempo y dinero", short: "Tiempo y dinero", blurb: "Tiempo al minuto. Tiempo transcurrido de una hora. Dinero hasta $5." },
    u12: { title: "Fluidez de multiplicar y dividir", short: "Fluidez", blurb: "Hasta 10 × 10, incluyendo 6 y 7." },
    u13: { title: "Seguir adelante y profundizar", short: "Profundizar", blurb: "Repaso del año, todavía un paseo, no un examen." },
  },
  "pt-BR": {
    u1: { title: "Construir uma comunidade matemática com o ciclo de dados", short: "Ciclo de dados", blurb: "Conte o que você vê. Junte e organize dados. Nomeie o que falta." },
    u2: { title: "Valor posicional / adição e subtração, parte 1", short: "Valor posicional", blurb: "Leia, escreva, monte, compare e ordene números até os milhares — até seis dígitos." },
    u3: { title: "Multiplicação e divisão parte 1 — sentido com modelos", short: "Sentido com modelos", blurb: "Grupos iguais, arranjos e fatos relacionados. Primeiro o significado." },
    u4: { title: "Geometria", short: "Geometria", blurb: "Identifique, descreva, classifique e compare. Una e divida triângulos e quadriláteros." },
    u5: { title: "Frações, parte 1", short: "Frações 1", blurb: "Próprias, impróprias e mistas. Modelos de região e de comprimento." },
    u6: { title: "Fatos fundamentais de multiplicar e dividir", short: "Fatos fáceis", blurb: "0, 1, 2, 5 e 10. Pictogramas com chave." },
    u7: { title: "Adição e subtração parte 2 — analisar o mundo e resolver", short: "Resolver problemas", blurb: "Histórias, gráficos e padrões. Estime e resolva até 1 000." },
    u8: { title: "Medida, perímetro e área", short: "Medida", blurb: "Comprimento, massa e volume — sistema usual e métrico. Depois cubra e contorne." },
    u9: { title: "Fatos de 3, 4, 8 e 9", short: "3 4 8 9", blurb: "Tabuadas de 3, 4, 8 e 9 em grupos e arranjos." },
    u10: { title: "Frações, parte 2", short: "Frações 2", blurb: "Equivalentes, comparar, pontos de referência e ordem." },
    u11: { title: "Tempo e dinheiro", short: "Tempo e dinheiro", blurb: "Tempo ao minuto. Tempo decorrido de uma hora. Dinheiro até $5." },
    u12: { title: "Fluência de multiplicar e dividir", short: "Fluência", blurb: "Até 10 × 10, incluindo 6 e 7." },
    u13: { title: "Seguir em frente e aprofundar", short: "Aprofundar", blurb: "Revisão do ano, ainda um passeio, não uma prova." },
  },
};

const ACT: Record<Exclude<Locale, "en">, Record<string, Act>> = {
  es: {
    "u1-leftover": { title: "Qué se esconde", blurb: "Marcos de diez. Toma los puntos que ves y nombra n." },
    "u1-friends": { title: "Amigos del número", blurb: "Suma y resta en un marco, hasta 20." },
    "u1-coins": { title: "Cuenta las monedas", blurb: "Centavos, nicoles, diez y veinticinco — hasta un dólar." },
    "u1-tally": { title: "Palitos y gráfica", blurb: "Clasifica. Mira crecer el pictograma. Luego léelo." },
    "u1-graph": { title: "Pictograma clave 1", blurb: "Lee un pictograma. Cada dibujo vale 1." },
    "u2-place": { title: "Lugar y valor", blurb: "Nombra el lugar y el valor de un dígito." },
    "u2-word": { title: "Forma en palabras", blurb: "Números de seis dígitos: palabras ↔ dígitos." },
    "u2-build": { title: "Componer y descomponer", blurb: "Arma un número hasta 9 999." },
    "u2-expanded": { title: "Decenas que ves", blurb: "60 + n = 64. Unidades que faltan." },
    "u2-compare": { title: "Comparar", blurb: "Mayor, menor o igual — hasta 9 999." },
    "u2-order": { title: "Pon en orden", blurb: "De menor a mayor, o al revés." },
    "u3-groups": { title: "Grupos iguales", blurb: "¿Cuántos grupos? ¿Cuántos en cada uno? ¿Cuántos en total?" },
    "u3-array": { title: "Arreglos", blurb: "Filas y columnas hacen un producto." },
    "u3-jumps": { title: "Saltos en la recta", blurb: "Saltos iguales sobre una recta numérica." },
    "u3-factor": { title: "Factor que falta", blurb: "2 × n = 8. Aísla un grupo y nombra n." },
    "u3-share": { title: "Repartir igual", blurb: "n grupos comparten el total. ¿Cuántos en cada uno?" },
    "u3-family": { title: "Hechos relacionados", blurb: "Un modelo, cuatro hechos." },
    "u4-name": { title: "Nombra la figura", blurb: "Mira el polígono. Nómbralo." },
    "u4-sides": { title: "Cuenta los lados", blurb: "¿Cuántos lados? ¿Cuántos vértices?" },
    "u4-vs": { title: "¿Polígono o no?", blurb: "Cerrado, lados rectos — o no." },
    "u4-attr": { title: "Atributos", blurb: "Lados, vértices y nombres juntos." },
    "u4-combine": { title: "Unir polígonos", blurb: "Dos triángulos hacen un polígono nuevo." },
    "u4-subdivide": { title: "Partir", blurb: "Parte un cuadrilátero. ¿Cuántos triángulos?" },
    "u5-name": { title: "Nombra la fracción", blurb: "Piezas sombreadas de una barra." },
    "u5-line": { title: "En una recta", blurb: "Un modelo de longitud. Nombra el punto." },
    "u5-unit": { title: "Fracciones unitarias", blurb: "Una pieza de n partes iguales." },
    "u5-leftover": { title: "Piezas que faltan", blurb: "Algunas piezas se ven. n se esconden." },
    "u5-mixed": { title: "Enteros y resto", blurb: "Números mixtos en barras apiladas." },
    "u5-set": { title: "De un conjunto", blurb: "Sombreados de un grupo del mismo tamaño." },
    "u6-facts": { title: "Hechos en grupos", blurb: "0, 1, 2, 5 y 10 como grupos iguales." },
    "u6-array": { title: "Arreglos fáciles", blurb: "Filas de 2, 5 o 10." },
    "u6-factor": { title: "Factor que falta", blurb: "5 × n = 30. Aísla un grupo." },
    "u6-skip": { title: "Contar de salto", blurb: "El patrón esconde un número." },
    "u6-picto": { title: "Palitos con clave", blurb: "Clasifica. Cada dibujo puede valer 1. Luego lee." },
    "u7-add": { title: "Juntar y lo que falta", blurb: "Una historia de juntar en un marco." },
    "u7-take": { title: "Quitar lo que falta", blurb: "Cuántos se esconden después de que algunos se van." },
    "u7-compare": { title: "Cuántos más", blurb: "Compara dos cantidades en una historia." },
    "u7-estimate": { title: "Más o menos cuántos", blurb: "Suma o resta hasta 1 000. Estima en centenas." },
    "u7-exact": { title: "Sumar y restar hasta 1 000", blurb: "Centenas, decenas y unidades que ves." },
    "u7-pattern": { title: "Crece y mengua", blurb: "Identifica, describe y alarga patrones +/−." },
    "u7-bar": { title: "Palitos en barras", blurb: "Clasifica. Las barras crecen. Luego responde." },
    "u8-length": { title: "Lee una regla", blurb: "Al medio o al entero, pulgada o centímetro." },
    "u8-mass": { title: "Peso y masa", blurb: "Una balanza. Onzas, libras, gramos, kilos." },
    "u8-volume": { title: "Volumen líquido", blurb: "Un vaso. Tazas, cuartos, mililitros, litros." },
    "u8-unit": { title: "Elige la unidad", blurb: "¿Estimación o exacta? ¿Pulgada o yarda?" },
    "u8-area": { title: "Cubre la cuadrícula", blurb: "¿Cuántos cuadrados unitarios?" },
    "u8-peri": { title: "Alrededor", blurb: "Perímetro de un polígono de hasta 6 lados." },
    "u8-missing": { title: "Lado que falta", blurb: "Sabes el perímetro. Un lado es n." },
    "u9-groups": { title: "Grupos de 3, 4, 8, 9", blurb: "Grupos iguales en esas tablas." },
    "u9-array": { title: "Arreglos", blurb: "Filas de 3, 4, 8 o 9." },
    "u9-factor": { title: "Factor que falta", blurb: "4 × n = 32. Aísla un grupo." },
    "u9-family": { title: "Hechos relacionados", blurb: "Un arreglo, cuatro hechos." },
    "u9-mix": { title: "Hechos mezclados", blurb: "× y ÷ en 3, 4, 8 y 9." },
    "u10-equiv": { title: "La misma cantidad", blurb: "Piezas distintas, la misma barra." },
    "u10-compare": { title: "¿Cuál es más?", blurb: "Dos barras, el mismo entero." },
    "u10-bench": { title: "Cerca de 0, ½, 1", blurb: "Compara la fracción con puntos de referencia." },
    "u10-order": { title: "Ordena fracciones", blurb: "De menor a mayor en barras." },
    "u10-line": { title: "Compara en una recta", blurb: "Dos puntos en una recta numérica." },
    "u11-clock": { title: "La hora al minuto", blurb: "Manecillas de hora y minuto." },
    "u11-match": { title: "Empareja relojes", blurb: "Una hora escrita y el reloj analógico." },
    "u11-elapsed": { title: "Una hora después", blurb: "Tiempo transcurrido de una hora." },
    "u11-count": { title: "Cuenta hasta $5", blurb: "Billetes y monedas hasta cinco dólares." },
    "u11-compare": { title: "Compara dinero", blurb: "¿Cuál conjunto es más?" },
    "u11-make": { title: "Arma esta cantidad", blurb: "Toca billetes y monedas hasta el total, hasta $5." },
    "u11-change": { title: "Da cambio", blurb: "Paga con billetes. n es lo que sobra." },
    "u12-six": { title: "6 y 7", blurb: "Las tablas que faltaban, todavía en grupos." },
    "u12-mix": { title: "Hechos mezclados", blurb: "Tablas 0–10, × y ÷, con 6 y 7." },
    "u12-factor": { title: "Factor mezclado", blurb: "Aísla un grupo, nombra n." },
    "u12-family": { title: "Familia mezclada", blurb: "Un modelo, cuatro hechos." },
    "u12-array": { title: "Arreglo del año", blurb: "Filas y columnas de todo el año." },
    "u13-two": { title: "Historias de dos pasos", blurb: "Y luego esto — con un modelo." },
    "u13-compute": { title: "Suma y resta mezclada", blurb: "Hasta 1 000, con centenas que ves." },
    "u13-pattern": { title: "Patrones numéricos", blurb: "Patrones +/− que crecen y menguan." },
    "u13-measure": { title: "Medir otra vez", blurb: "Una regla, una balanza o un vaso del año." },
    "u13-area": { title: "Historias de área", blurb: "Cubrir un espacio en una historia." },
  },
  "pt-BR": {
    "u1-leftover": { title: "O que está escondido", blurb: "Quadros de dez. Pegue os pontos que você vê e nomeie n." },
    "u1-friends": { title: "Amigos do número", blurb: "Some e subtraia num quadro, até 20." },
    "u1-coins": { title: "Conte as moedas", blurb: "Centavos, níqueis, dez e vinte e cinco — até um dólar." },
    "u1-tally": { title: "Riscos e gráfico", blurb: "Classifique. Veja o pictograma crescer. Depois leia." },
    "u1-graph": { title: "Pictograma chave 1", blurb: "Leia um pictograma. Cada figura vale 1." },
    "u2-place": { title: "Ordem e valor", blurb: "Nomeie a ordem e o valor de um dígito." },
    "u2-word": { title: "Forma por extenso", blurb: "Números de seis dígitos: palavras ↔ dígitos." },
    "u2-build": { title: "Compor e decompor", blurb: "Monte um número até 9 999." },
    "u2-expanded": { title: "Dezenas que você vê", blurb: "60 + n = 64. Unidades que faltam." },
    "u2-compare": { title: "Comparar", blurb: "Maior, menor ou igual — até 9 999." },
    "u2-order": { title: "Coloque em ordem", blurb: "Do menor ao maior, ou o contrário." },
    "u3-groups": { title: "Grupos iguais", blurb: "Quantos grupos? Quantos em cada? Quantos no total?" },
    "u3-array": { title: "Arranjos", blurb: "Fileiras e colunas fazem um produto." },
    "u3-jumps": { title: "Saltos na reta", blurb: "Saltos iguais numa reta numérica." },
    "u3-factor": { title: "Fator que falta", blurb: "2 × n = 8. Isole um grupo e nomeie n." },
    "u3-share": { title: "Repartir igual", blurb: "n grupos compartilham o total. Quantos em cada?" },
    "u3-family": { title: "Fatos relacionados", blurb: "Um modelo, quatro fatos." },
    "u4-name": { title: "Nomeie a forma", blurb: "Olhe o polígono. Nomeie." },
    "u4-sides": { title: "Conte os lados", blurb: "Quantos lados? Quantos vértices?" },
    "u4-vs": { title: "Polígono ou não?", blurb: "Fechado, lados retos — ou não." },
    "u4-attr": { title: "Atributos", blurb: "Lados, vértices e nomes juntos." },
    "u4-combine": { title: "Unir polígonos", blurb: "Dois triângulos fazem um polígono novo." },
    "u4-subdivide": { title: "Dividir", blurb: "Divida um quadrilátero. Quantos triângulos?" },
    "u5-name": { title: "Nomeie a fração", blurb: "Pedaços sombreados de uma barra." },
    "u5-line": { title: "Numa reta", blurb: "Um modelo de comprimento. Nomeie o ponto." },
    "u5-unit": { title: "Frações unitárias", blurb: "Um pedaço de n partes iguais." },
    "u5-leftover": { title: "Pedaços que faltam", blurb: "Alguns pedaços aparecem. n se escondem." },
    "u5-mixed": { title: "Inteiros e resto", blurb: "Números mistos em barras empilhadas." },
    "u5-set": { title: "De um conjunto", blurb: "Sombreados de um grupo do mesmo tamanho." },
    "u6-facts": { title: "Fatos em grupos", blurb: "0, 1, 2, 5 e 10 como grupos iguais." },
    "u6-array": { title: "Arranjos fáceis", blurb: "Fileiras de 2, 5 ou 10." },
    "u6-factor": { title: "Fator que falta", blurb: "5 × n = 30. Isole um grupo." },
    "u6-skip": { title: "Contar pulando", blurb: "O padrão esconde um número." },
    "u6-picto": { title: "Riscos com chave", blurb: "Classifique. Cada figura pode valer 1. Depois leia." },
    "u7-add": { title: "Juntar e o que falta", blurb: "Uma história de juntar num quadro." },
    "u7-take": { title: "Tirar o que falta", blurb: "Quantos se escondem depois que alguns saem." },
    "u7-compare": { title: "Quantos a mais", blurb: "Compare duas quantidades numa história." },
    "u7-estimate": { title: "Mais ou menos quantos", blurb: "Some ou subtraia até 1 000. Estime em centenas." },
    "u7-exact": { title: "Somar e subtrair até 1 000", blurb: "Centenas, dezenas e unidades que você vê." },
    "u7-pattern": { title: "Cresce e diminui", blurb: "Identifique, descreva e estenda padrões +/−." },
    "u7-bar": { title: "Riscos em barras", blurb: "Classifique. As barras crescem. Depois responda." },
    "u8-length": { title: "Leia uma régua", blurb: "Ao meio ou ao inteiro, polegada ou centímetro." },
    "u8-mass": { title: "Peso e massa", blurb: "Uma balança. Onças, libras, gramas, quilos." },
    "u8-volume": { title: "Volume líquido", blurb: "Um copo. Xícaras, quartos, mililitros, litros." },
    "u8-unit": { title: "Escolha a unidade", blurb: "Estimativa ou exata? Polegada ou jarda?" },
    "u8-area": { title: "Cubra a grade", blurb: "Quantos quadrados unitários?" },
    "u8-peri": { title: "Ao redor", blurb: "Perímetro de um polígono de até 6 lados." },
    "u8-missing": { title: "Lado que falta", blurb: "Você sabe o perímetro. Um lado é n." },
    "u9-groups": { title: "Grupos de 3, 4, 8, 9", blurb: "Grupos iguais nessas tabuadas." },
    "u9-array": { title: "Arranjos", blurb: "Fileiras de 3, 4, 8 ou 9." },
    "u9-factor": { title: "Fator que falta", blurb: "4 × n = 32. Isole um grupo." },
    "u9-family": { title: "Fatos relacionados", blurb: "Um arranjo, quatro fatos." },
    "u9-mix": { title: "Fatos mistos", blurb: "× e ÷ em 3, 4, 8 e 9." },
    "u10-equiv": { title: "A mesma quantidade", blurb: "Pedaços diferentes, a mesma barra." },
    "u10-compare": { title: "Qual é maior?", blurb: "Duas barras, o mesmo inteiro." },
    "u10-bench": { title: "Perto de 0, ½, 1", blurb: "Compare a fração com pontos de referência." },
    "u10-order": { title: "Ordene frações", blurb: "Do menor ao maior em barras." },
    "u10-line": { title: "Compare numa reta", blurb: "Dois pontos numa reta numérica." },
    "u11-clock": { title: "Hora ao minuto", blurb: "Ponteiros de hora e minuto." },
    "u11-match": { title: "Combine relógios", blurb: "Uma hora escrita e o relógio analógico." },
    "u11-elapsed": { title: "Uma hora depois", blurb: "Tempo decorrido de uma hora." },
    "u11-count": { title: "Conte até $5", blurb: "Notas e moedas até cinco dólares." },
    "u11-compare": { title: "Compare dinheiro", blurb: "Qual conjunto é maior?" },
    "u11-make": { title: "Monte esta quantia", blurb: "Toque notas e moedas até o total, até $5." },
    "u11-change": { title: "Dê o troco", blurb: "Pague com notas. n é o que sobra." },
    "u12-six": { title: "6 e 7", blurb: "As tabuadas que faltavam, ainda em grupos." },
    "u12-mix": { title: "Fatos mistos", blurb: "Tabuadas 0–10, × e ÷, com 6 e 7." },
    "u12-factor": { title: "Fator misto", blurb: "Isole um grupo, nomeie n." },
    "u12-family": { title: "Família mista", blurb: "Um modelo, quatro fatos." },
    "u12-array": { title: "Arranjo do ano", blurb: "Fileiras e colunas do ano inteiro." },
    "u13-two": { title: "Histórias de dois passos", blurb: "E depois isto — com um modelo." },
    "u13-compute": { title: "Soma e subtração mista", blurb: "Até 1 000, com centenas que você vê." },
    "u13-pattern": { title: "Padrões numéricos", blurb: "Padrões +/− que crescem e diminuem." },
    "u13-measure": { title: "Medir de novo", blurb: "Uma régua, uma balança ou um copo do ano." },
    "u13-area": { title: "Histórias de área", blurb: "Cobrir um espaço numa história." },
  },
};

export function unitText(unit: { id: string; title: string; short: string; blurb: string }, locale: Locale): Text {
  if (locale === "en") return { title: unit.title, short: unit.short, blurb: unit.blurb };
  return UNIT[locale][unit.id] ?? { title: unit.title, short: unit.short, blurb: unit.blurb };
}

export function activityText(activity: { id: string; title: string; blurb: string }, locale: Locale): Act {
  if (locale === "en") return { title: activity.title, blurb: activity.blurb };
  return ACT[locale][activity.id] ?? { title: activity.title, blurb: activity.blurb };
}
