export const SIGHT_LEVELS = ["preprimer", "primer", "first", "second", "third"] as const;
export type SightList = (typeof SIGHT_LEVELS)[number];

export interface SightWord {
  id: string;
  word: string;
  list: SightList;
  emoji: string;
  sentence: string;
}

function pack(list: SightList, rows: ReadonlyArray<readonly [string, string, string]>): SightWord[] {
  return rows.map(([word, emoji, sentence]) => ({
    id: `sw:${word.toLowerCase()}`,
    word,
    list,
    emoji,
    sentence,
  }));
}

/** Dolch pre-primer. */
const PREPRIMER = pack("preprimer", [
  ["a", "", "I have a dog."],
  ["and", "", "We hop and skip."],
  ["away", "🐦", "The bird flew away."],
  ["big", "🐘", "The elephant is big."],
  ["blue", "🔵", "The hat is blue."],
  ["can", "", "Birds can fly."],
  ["come", "👋", "Come play with us."],
  ["down", "⬇️", "Sit down please."],
  ["find", "🔍", "I find my bear."],
  ["for", "", "This gift is for Mom."],
  ["funny", "😄", "The clown is funny."],
  ["go", "🚶", "Go to the door."],
  ["help", "🤝", "Please help me."],
  ["here", "📍", "Sit here by me."],
  ["I", "", "I like stories."],
  ["in", "", "The toy is in the box."],
  ["is", "", "Soup is warm."],
  ["it", "", "I can hold it."],
  ["jump", "🐸", "Frogs jump high."],
  ["little", "🐞", "A little bug sat."],
  ["look", "👀", "Look at the moon."],
  ["make", "🎂", "We make a cake."],
  ["me", "", "Wave at me."],
  ["my", "🧸", "This is my bear."],
  ["not", "", "I am not sad."],
  ["one", "1️⃣", "I see one star."],
  ["play", "🎈", "We play tag."],
  ["red", "🔴", "The ball is red."],
  ["run", "🏃", "I run fast."],
  ["said", "", "Mom said hello."],
  ["see", "⭐", "I see a star."],
  ["the", "", "The cat sat."],
  ["three", "3️⃣", "I count three ducks."],
  ["to", "", "I like to read."],
  ["two", "2️⃣", "I have two shoes."],
  ["up", "⬆️", "The balloon went up."],
  ["we", "", "We like jokes."],
  ["where", "❓", "Where is the dog?"],
  ["yellow", "🟡", "The sun is yellow."],
  ["you", "", "You are kind."],
]);

/** Dolch primer. */
const PRIMER = pack("primer", [
  ["all", "", "We shared all the crayons."],
  ["am", "", "I am happy."],
  ["are", "", "You are kind."],
  ["at", "", "Look at the stars."],
  ["ate", "🍐", "I ate a pear."],
  ["be", "", "I will be brave."],
  ["black", "⬛", "The cat is black."],
  ["brown", "🐻", "The bear is brown."],
  ["but", "", "I am small but brave."],
  ["came", "", "My pal came over."],
  ["did", "", "I did my best."],
  ["do", "", "I do like cats."],
  ["eat", "🍎", "I eat an apple."],
  ["four", "4️⃣", "I see four birds."],
  ["get", "", "I get a hug."],
  ["good", "👍", "That was a good try."],
  ["have", "🪁", "I have a kite."],
  ["he", "", "He can jump."],
  ["into", "🐸", "The frog hopped into the pond."],
  ["like", "", "I like apples."],
  ["must", "", "We must be kind."],
  ["new", "👟", "I have new shoes."],
  ["no", "", "The answer is no."],
  ["now", "", "We can play now."],
  ["on", "", "The hat is on the hook."],
  ["our", "🏠", "This is our house."],
  ["out", "", "We go out to play."],
  ["please", "🙏", "Please sit with me."],
  ["pretty", "🌸", "The flower is pretty."],
  ["ran", "🏃", "The puppy ran home."],
  ["ride", "🚲", "I ride a bike."],
  ["saw", "👀", "I saw a robin."],
  ["say", "", "We say hello."],
  ["she", "", "She can sing."],
  ["so", "", "I am so glad."],
  ["soon", "", "Lunch is soon."],
  ["that", "", "I want that book."],
  ["there", "", "The park is over there."],
  ["they", "", "They like stories."],
  ["this", "", "This is my dog."],
  ["too", "", "I want a turn too."],
  ["under", "🛏️", "The cat is under the bed."],
  ["want", "", "I want a turn."],
  ["was", "", "The dog was wet."],
  ["well", "", "You did well."],
  ["went", "", "We went outside."],
  ["what", "", "What is your name?"],
  ["white", "🥛", "The milk is white."],
  ["who", "", "Who is at the door?"],
  ["will", "", "I will help."],
  ["with", "", "Come with me."],
  ["yes", "", "Yes we can share."],
]);

/** Dolch first grade. */
const FIRST = pack("first", [
  ["after", "", "We rest after lunch."],
  ["again", "", "Let us read again."],
  ["an", "", "I see an owl."],
  ["any", "", "Any friend can join."],
  ["as", "", "We run as a team."],
  ["ask", "", "Ask a question."],
  ["by", "", "Sit by the tree."],
  ["could", "", "We could build a fort."],
  ["every", "", "Every duck can swim."],
  ["fly", "🦋", "Butterflies fly by."],
  ["from", "", "The note is from Dad."],
  ["give", "", "Give the dog a pat."],
  ["going", "", "I am going home."],
  ["had", "", "I had a snack."],
  ["has", "", "She has a kite."],
  ["her", "", "This is her book."],
  ["him", "", "I sit with him."],
  ["his", "", "His hat is red."],
  ["how", "", "How are you today?"],
  ["just", "", "I just got here."],
  ["know", "", "I know that song."],
  ["let", "", "Let me help."],
  ["live", "", "We live by a hill."],
  ["may", "", "You may have a turn."],
  ["of", "", "A cup of milk."],
  ["old", "", "My turtle is old."],
  ["once", "", "Once I saw a fox."],
  ["open", "🚪", "Open the door."],
  ["over", "", "The kite flew over the barn."],
  ["put", "", "Put the book here."],
  ["round", "🟠", "The orange is round."],
  ["some", "", "Have some milk."],
  ["stop", "🛑", "Stop at the line."],
  ["take", "", "Take my hand."],
  ["thank", "", "Thank you for the help."],
  ["them", "", "I can see them."],
  ["then", "", "We snack and then play."],
  ["think", "", "I think this is fun."],
  ["walk", "🚶", "We walk to the park."],
  ["were", "", "We were at the zoo."],
  ["when", "", "When can we play?"],
]);

/** Dolch second grade, plus Fry words that are not already on a Dolch list. */
const SECOND = pack("second", [
  ["always", "", "I always wave hello."],
  ["around", "", "We run around the yard."],
  ["because", "", "I smile because I am glad."],
  ["been", "", "I have been outside."],
  ["before", "", "Wash before lunch."],
  ["best", "", "You did your best."],
  ["both", "", "Both shoes are tied."],
  ["buy", "🛒", "We buy apples."],
  ["call", "", "Call me at home."],
  ["cold", "❄️", "The snow is cold."],
  ["does", "", "She does her best."],
  ["don't", "", "Please don't run."],
  ["fast", "🐇", "The rabbit is fast."],
  ["first", "🥇", "I am first in line."],
  ["five", "5️⃣", "I have five crayons."],
  ["found", "", "I found my hat."],
  ["gave", "", "Mom gave me a hug."],
  ["goes", "", "The bus goes by."],
  ["green", "🟢", "The frog is green."],
  ["its", "", "The dog wags its tail."],
  ["made", "", "We made a fort."],
  ["many", "", "Many stars are out."],
  ["off", "", "The lamp is off."],
  ["or", "", "Cat or dog?"],
  ["pull", "", "Pull the wagon."],
  ["read", "📖", "I read a story."],
  ["right", "", "Turn right at the oak."],
  ["sing", "🎤", "We sing a song."],
  ["sit", "🪑", "Sit on the rug."],
  ["sleep", "😴", "The baby can sleep."],
  ["tell", "", "Tell me a joke."],
  ["their", "", "Their dog is fluffy."],
  ["these", "", "These are my blocks."],
  ["those", "", "Those birds can sing."],
  ["upon", "", "The cat sat upon a mat."],
  ["us", "", "Come with us."],
  ["use", "", "We use a pencil."],
  ["very", "", "I am very happy."],
  ["wash", "🧼", "Wash your hands."],
  ["which", "", "Which hat is blue?"],
  ["why", "", "Why is the sky blue?"],
  ["wish", "", "I wish for a puppy."],
  ["work", "", "We work as a team."],
  ["would", "", "I would like a turn."],
  ["write", "✏️", "I write my name."],
  ["your", "", "This is your seat."],
  ["boy", "👦", "The boy has a kite."],
  ["day", "☀️", "It is a sunny day."],
  ["house", "🏠", "We play at the house."],
  ["mother", "", "My mother reads with me."],
  ["name", "", "My name is Mia."],
  ["school", "🏫", "We go to school."],
  ["thing", "", "What is that thing?"],
  ["time", "⏰", "It is time for lunch."],
  ["water", "💧", "I drink water."],
  ["way", "", "This is the way home."],
]);

/** Dolch third grade, plus Fry words that are not already on a Dolch list. */
const THIRD = pack("third", [
  ["about", "", "Tell me about your day."],
  ["better", "", "I feel better now."],
  ["bring", "", "Bring a coat."],
  ["carry", "", "I carry my bag."],
  ["clean", "🧽", "We clean the table."],
  ["cut", "✂️", "Cut the paper."],
  ["done", "", "My work is done."],
  ["draw", "✏️", "I draw a cat."],
  ["drink", "🥤", "I drink milk."],
  ["eight", "8️⃣", "I count eight stars."],
  ["fall", "🍂", "Leaves fall down."],
  ["far", "", "The store is far."],
  ["full", "", "The cup is full."],
  ["got", "", "I got a sticker."],
  ["grow", "🌱", "Seeds grow in soil."],
  ["hold", "", "Hold my hand."],
  ["hot", "🔥", "The soup is hot."],
  ["hurt", "", "My knee does not hurt."],
  ["if", "", "We can play if it is dry."],
  ["keep", "", "Keep your coat on."],
  ["kind", "", "Be kind to pets."],
  ["laugh", "😂", "Jokes make me laugh."],
  ["light", "💡", "The light is on."],
  ["long", "", "The snake is long."],
  ["much", "", "Thank you so much."],
  ["myself", "", "I tied it myself."],
  ["never", "", "I never give up."],
  ["only", "", "I have only one pencil."],
  ["own", "", "I have my own cup."],
  ["pick", "🍎", "Pick a red apple."],
  ["seven", "7️⃣", "I see seven fish."],
  ["shall", "", "Shall we read now?"],
  ["show", "", "Show me your picture."],
  ["six", "6️⃣", "I have six blocks."],
  ["small", "🐜", "The ant is small."],
  ["start", "", "Start at the top."],
  ["ten", "🔟", "I can count to ten."],
  ["today", "📅", "Today we paint."],
  ["together", "", "We read together."],
  ["try", "", "Try a new game."],
  ["warm", "☀️", "The sand is warm."],
  ["number", "🔢", "What number comes next?"],
  ["people", "👥", "The people smile."],
  ["word", "", "Read the next word."],
  ["more", "", "I would like more soup."],
  ["other", "", "The other hat is blue."],
  ["each", "", "Give one to each friend."],
  ["part", "", "This is part of the story."],
  ["family", "👨‍👩‍👧", "My family is kind."],
  ["different", "", "The socks are different."],
  ["answer", "", "I know the answer."],
  ["city", "🏙️", "The city has tall buildings."],
  ["animal", "🐶", "A dog is an animal."],
  ["earth", "🌍", "We live on the earth."],
  ["story", "📚", "Read me a story."],
  ["eye", "👁️", "I see with my eye."],
  ["head", "", "The hat is on my head."],
  ["young", "🐣", "The chick is young."],
  ["example", "", "Here is an example."],
  ["important", "", "Water is important."],
  ["mountain", "⛰️", "The mountain is tall."],
]);

const BY_LIST: Record<SightList, readonly SightWord[]> = {
  preprimer: PREPRIMER,
  primer: PRIMER,
  first: FIRST,
  second: SECOND,
  third: THIRD,
};

export const ALL_SIGHT: readonly SightWord[] = [...PREPRIMER, ...PRIMER, ...FIRST, ...SECOND, ...THIRD];

export function sightWords(list: SightList): readonly SightWord[] {
  return BY_LIST[list];
}

export function isSightList(value: unknown): value is SightList {
  return typeof value === "string" && (SIGHT_LEVELS as readonly string[]).includes(value);
}
